command:
  - streamlit
  - run
  - app.py
  - --server.port=8080
  - --server.address=0.0.0.0

env:
  - name: DATABRICKS_SERVER_HOSTNAME
    value: "dbc-68a1cdfa-43b8.cloud.databricks.com"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/a823ad30eae0e044"
  - name: DATABRICKS_TOKEN
    value: "YOUR_ACCESS_TOKEN_HERE"  # Generate from User Settings > Access Tokens
